# Always generate Python 3.13-compatible code.
target-version = "py313"
line-length = 100
fix = true

[lint]
select = ["ALL"]
ignore = [
    "COM",
    "D",
    "TD",
    # Recommended ignores if Ruff formatter is used
    "W191",
    "E111",
    "E114",
    "E117",
    "D206",
    "D300",
    "Q000",
    "Q001",
    "Q002",
    "Q003",
    "COM812",
    "COM819",
    "ISC002",
]

[lint.pylint]
max-branches = 5
max-locals = 5
max-statements = 15

[lint.per-file-ignores]
"tests/*" = ["ANN001", "ANN201", "INP001", "S101"]

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
