from models import Nota, Tag, Task  # noqa: INP001

task_list: list[Task] = [
    Task(
        id=1,
        titol="Task example",
        tipus=Tag.PROJECT,
        deadline="21 Dec",
        reminder="20 Dec, 9:00 AM",
        is_selected=True,
        is_done=False,
    ),
    Task(
        id=2,
        titol="Dummy 101",
        tipus=Tag.PERSONAL,
        deadline="21 Dec",
        reminder="20 Dec, 9:00 AM",
        is_selected=False,
        is_done=False,
    ),
    Task(
        id=3,
        titol="Test 123",
        tipus=Tag.OTHER,
        deadline=None,
        reminder=None,
        is_selected=False,
        is_done=False,
    ),  # ejemeplo nota
    Task(
        id=4,
        titol="Test 456",
        tipus=Tag.OTHER,
        deadline=None,
        reminder=None,
        is_selected=False,
        is_done=False,
    ),
]


nota_list: list[Nota] = [
    Nota(
        id=1,
        titol="Brainstorming Session Highlights",
        contingut="Capture your team's best ideas here. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eget augue ante. Integer hendrerit aliquam arcu at laoreet. Duis ac volutpat mi, porta laoreet lorem. Mauris et maximus nibh.",  # noqa: E501
        link="https://contoso.sharepoint.com/sites/Admins.... exemple link created",
        tasks=task_list,
        tasks_id=[1, 2, 3],
        has_tasks=True,
        num_links=3,
        tags=Tag.PERSONAL,
        num_tags=2,
        time="03:20 PM",
        notebook="NoteBook-01",
        has_alarm=True,
        is_shared=False,
        images=["livingroom.jpg"],
        last_edit="Dec 13, 2021",
    ),
    Nota(
        id=2,
        titol="Helping a local business",
        contingut="Amet minim mollit non deserunt illemco est Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eget augue ante. Integer hendrerit aliquam arcu at laoreet. Duis ac volutpat mi, porta laoreet lorem. Mauris et maximus nibh.",  # noqa: E501
        link=None,
        tasks=task_list,
        tasks_id=[1, 2, 3],
        has_tasks=True,
        num_links=3,
        tags=Tag.PROJECT,
        num_tags=2,
        time="11:24 AM",
        notebook="NoteBook-01",
        has_alarm=False,
        is_shared=False,
        images=["livingroom2.jpg"],
        last_edit="Dec 13, 2021",
    ),
    Nota(
        id=3,
        titol="Weekly Team Update",
        contingut="Document this week's accomplishments, challenges . . . .Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eget augue ante. Integer hendrerit aliquam arcu at laoreet. Duis ac volutpat mi, porta laoreet lorem. Mauris et maximus nibh.",  # noqa: E501
        link="https://www.google.com/",
        tasks=task_list,
        tasks_id=[1, 2, 3],
        has_tasks=False,
        num_links=0,
        tags=None,
        num_tags=2,
        time="09:02 AM",
        notebook="NoteBook-01",
        has_alarm=False,
        is_shared=False,
        images=None,
        last_edit="Dec 13, 2021",
    ),
    Nota(
        id=4,
        titol="Streamline Your Workflow with a good environment",
        contingut="In today's fast-paced environment, staying organized is the key to succedd. Use this space to jot down important ideas, action plans, or meeting notes. With integrated task mangament, you can turn your thoughts into actionable steps with deadlines and labels. Keep your team aligned by sharing updates and progress in real-time. Stay ahead prioritizing what matters the most.",  # noqa: E501
        link="https://www.mozilla.org/es-ES/",
        tasks=task_list,
        tasks_id=[1, 2, 3],
        has_tasks=True,
        num_links=3,
        tags=Tag.PERSONAL,
        num_tags=2,
        time="10:20 AM",
        notebook="NoteBook-01",
        has_alarm=True,
        is_shared=True,
        images=["livingroom.jpg"],
        last_edit="Dec 13, 2021",
    ),
    Nota(
        id=5,
        titol="Client Meeting Notes",
        contingut="Keep a record of all client interactions in one place. \n Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eget augue ante. Integer hendrerit aliquam arcu at laoreet. Duis ac volutpat mi, porta laoreet lorem. Mauris et maximus nibh.",  # noqa: E501
        link=None,
        tasks=task_list,
        tasks_id=[1, 2],
        has_tasks=True,
        num_links=3,
        tags=Tag.PERSONAL,
        num_tags=2,
        time="04:53 AM",
        notebook="NoteBook-01",
        has_alarm=False,
        is_shared=False,
        images=None,
        last_edit="Feb 23, 2022",
    ),
    Nota(
        id=6,
        titol="Project Kickoff Plan",
        contingut="Lay out the initial roadmap for your ner project. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eget augue ante. Integer hendrerit aliquam arcu at laoreet. Duis ac volutpat mi, porta laoreet lorem. Mauris et maximus nibh.",  # noqa: E501
        link="https://www.mozilla.org/es-ES/",
        tasks=task_list,
        tasks_id=[1, 2, 3],
        has_tasks=True,
        num_links=0,
        tags=Tag.PROJECT,
        num_tags=0,
        time="10:43 AM",
        notebook="NoteBook-01",
        has_alarm=False,
        is_shared=False,
        images=None,
        last_edit="Dec 13, 2021",
    ),  # ejemplo para tasks
    Nota(
        id=7,
        titol="Ejemplo tasks",
        contingut="Ejemplo !!!!!!!!!!!!!!!!!!!. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eget augue ante. Integer hendrerit aliquam arcu at laoreet. Duis ac volutpat mi, porta laoreet lorem. Mauris et maximus nibh.",  # noqa: E501
        link=None,
        tasks=task_list,
        tasks_id=[4],
        has_tasks=True,
        num_links=0,
        tags=Tag.PROJECT,
        num_tags=0,
        time="10:43 AM",
        notebook="NoteBook-01",
        has_alarm=False,
        is_shared=False,
        images=["livingroom2.jpg", "livingroom.jpg"],
        last_edit="Dec 13, 2021",
    ),
]
